version: "3.9"

services:
  # .NET CONTAINER
  wishapi:
    container_name: wishapi
    build:
      context: ./Wish-Jewelry-Shop
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+;http://+:5000"
    restart: always
  webserver:
    container_name: webserver
    build:
      context: ./Wish.UI
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always 
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/certbot -d dev-wish.ru --non-interactive --agree-tos --register-unsafely-without-email --staging
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw