using FluentMigrator;
using Wish.Persistence.Common;

namespace Wish.Persistence.Migrations;

[Migration(3, "Audit and AuditMetaData tables")]
public class AuditTables : SqlMigration
{
    protected override string GetUpSql(IServiceProvider services) => @"
create table audit_meta_data (
    id bigint generated by default as identity
        constraint pk_audit_meta_data
            primary key,
    schema_table text not null,
    table_name text not null,
    schema text not null,
    hash_primary_key text not null,
    readable_primary_key text not null
);
create table audits (
    id bigint generated by default as identity
        constraint pk_audits
            primary key,
    audit_meta_data_id bigint not null
        constraint fk_audits_audit_meta_data_id__audit_meta_data_id
            references audit_meta_data
            on delete cascade,
    created_at timestamp not null,
    old_values text,
    new_values text,
    entity_state integer not null,
    created_by bigint 
        constraint fk_audit_tables_created_by__identity_users_user_id
            references identity_users
            on delete cascade
);
";

    protected override string GetDownSql(IServiceProvider services) => @"
drop table if exists audits;
drop table if exists audit_meta_data;
";
}
