using FluentMigrator;
using Wish.Persistence.Common;

namespace Wish.Persistence.Migrations;

[Migration(5, "Categories Table")]
public class CategoriesTable : SqlMigration
{
	protected override string GetUpSql(IServiceProvider services) => @"
	create table categories(

	id bigint generated by default as identity
		constraint pk_categories
		primary key,
	title text not null
);
";
	

    protected override string GetDownSql(IServiceProvider services) => @"
	drop table if exists categories;
";
}
