using FluentMigrator;
using Wish.Persistence.Common;

namespace Wish.Persistence.Migrations;

[Migration(6, "Create Materials Table")]
public class CreateMaterialsTable : SqlMigration
{
	protected override string GetUpSql(IServiceProvider services) => @"
	
	create table materials(

	id bigint generated by default as identity
		constraint pk_materials
		primary key,
	type bigint not null,
	title text not null

);
";

    protected override string GetDownSql(IServiceProvider services) => @"
	drop table if exists materials;
";
}