using FluentMigrator;
using Wish.Persistence.Common;

namespace Wish.Persistence.Migrations;

[Migration(9, "Products Table")]
public class ProductsTable : SqlMigration
{
	protected override string GetUpSql(IServiceProvider services) => @"
	create table products(

	id bigint generated by default as identity
		constraint pk_products
		primary key,
	title text not null,

	description text not null,

	category_id bigint not null
		constraint fk_products__categories_id
		references categories
        on delete cascade,

	picture_link text not null,

	material bigint not null
		constraint fk_products__materials_id
		references materials
		on delete cascade,

	weight decimal not null,

	count bigint not null,

	price decimal not null
);
";

    protected override string GetDownSql(IServiceProvider services) => @"
	drop table if exists products;
";
}
